//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(OPMS.Data.Context.ContextDb),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsbb0e7275c4d8bfd57e5bbf1db8dfe13982b8abe4cba2264143c4a962cf75c5a4))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework 6 Power Tools", "0.9.2.0")]
    internal sealed class ViewsForBaseEntitySetsbb0e7275c4d8bfd57e5bbf1db8dfe13982b8abe4cba2264143c4a962cf75c5a4 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "bb0e7275c4d8bfd57e5bbf1db8dfe13982b8abe4cba2264143c4a962cf75c5a4"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "CodeFirstDatabase.AboutPage")
            {
                return GetView0();
            }

            if (extentName == "CodeFirstDatabase.AboutSection")
            {
                return GetView1();
            }

            if (extentName == "CodeFirstDatabase.AboutShortSection")
            {
                return GetView2();
            }

            if (extentName == "ContextDb.AboutPages")
            {
                return GetView3();
            }

            if (extentName == "ContextDb.AboutSections")
            {
                return GetView4();
            }

            if (extentName == "ContextDb.AboutShortSections")
            {
                return GetView5();
            }

            if (extentName == "CodeFirstDatabase.AdminActivity")
            {
                return GetView6();
            }

            if (extentName == "ContextDb.AdminActivities")
            {
                return GetView7();
            }

            if (extentName == "CodeFirstDatabase.AdminstratorPanel")
            {
                return GetView8();
            }

            if (extentName == "ContextDb.AdminstratorPanels")
            {
                return GetView9();
            }

            if (extentName == "CodeFirstDatabase.ContactDetails")
            {
                return GetView10();
            }

            if (extentName == "CodeFirstDatabase.ContactInfo")
            {
                return GetView11();
            }

            if (extentName == "CodeFirstDatabase.ContactMainPage")
            {
                return GetView12();
            }

            if (extentName == "CodeFirstDatabase.Contact")
            {
                return GetView13();
            }

            if (extentName == "ContextDb.ContactDetails")
            {
                return GetView14();
            }

            if (extentName == "ContextDb.ContactInfos")
            {
                return GetView15();
            }

            if (extentName == "ContextDb.ContactPages")
            {
                return GetView16();
            }

            if (extentName == "ContextDb.Contacts")
            {
                return GetView17();
            }

            if (extentName == "CodeFirstDatabase.HelpSupport")
            {
                return GetView18();
            }

            if (extentName == "ContextDb.HelpSupports")
            {
                return GetView19();
            }

            if (extentName == "CodeFirstDatabase.HomeBanner")
            {
                return GetView20();
            }

            if (extentName == "CodeFirstDatabase.Page")
            {
                return GetView21();
            }

            if (extentName == "CodeFirstDatabase.HomeContent")
            {
                return GetView22();
            }

            if (extentName == "CodeFirstDatabase.Sidebar")
            {
                return GetView23();
            }

            if (extentName == "ContextDb.HomeBanners")
            {
                return GetView24();
            }

            if (extentName == "ContextDb.Pages")
            {
                return GetView25();
            }

            if (extentName == "ContextDb.HomeContents")
            {
                return GetView26();
            }

            if (extentName == "ContextDb.Sidebars")
            {
                return GetView27();
            }

            if (extentName == "CodeFirstDatabase.HomeRR")
            {
                return GetView28();
            }

            if (extentName == "ContextDb.HomeRolesResponsibilities")
            {
                return GetView29();
            }

            if (extentName == "CodeFirstDatabase.MainPostSystem")
            {
                return GetView30();
            }

            if (extentName == "CodeFirstDatabase.PostSystem")
            {
                return GetView31();
            }

            if (extentName == "CodeFirstDatabase.SocialWorker")
            {
                return GetView32();
            }

            if (extentName == "CodeFirstDatabase.UserModel")
            {
                return GetView33();
            }

            if (extentName == "CodeFirstDatabase.RoleModel")
            {
                return GetView34();
            }

            if (extentName == "CodeFirstDatabase.MessageContainer")
            {
                return GetView35();
            }

            if (extentName == "CodeFirstDatabase.Messages")
            {
                return GetView36();
            }

            if (extentName == "CodeFirstDatabase.UserModelRoleModel")
            {
                return GetView37();
            }

            if (extentName == "ContextDb.MainPostSystems")
            {
                return GetView38();
            }

            if (extentName == "ContextDb.PostSystems")
            {
                return GetView39();
            }

            if (extentName == "ContextDb.SocialWorkers")
            {
                return GetView40();
            }

            if (extentName == "ContextDb.Users")
            {
                return GetView41();
            }

            if (extentName == "ContextDb.Roles")
            {
                return GetView42();
            }

            if (extentName == "ContextDb.MessageContainers")
            {
                return GetView43();
            }

            if (extentName == "ContextDb.Messages")
            {
                return GetView44();
            }

            if (extentName == "ContextDb.UserModel_Roles")
            {
                return GetView45();
            }

            if (extentName == "CodeFirstDatabase.Menu")
            {
                return GetView46();
            }

            if (extentName == "ContextDb.Menus")
            {
                return GetView47();
            }

            if (extentName == "CodeFirstDatabase.NewsBanner")
            {
                return GetView48();
            }

            if (extentName == "CodeFirstDatabase.NewsInfo")
            {
                return GetView49();
            }

            if (extentName == "ContextDb.NewsBanners")
            {
                return GetView50();
            }

            if (extentName == "ContextDb.NewsInfos")
            {
                return GetView51();
            }

            if (extentName == "CodeFirstDatabase.SiteSettings")
            {
                return GetView52();
            }

            if (extentName == "ContextDb.SiteSettings")
            {
                return GetView53();
            }

            if (extentName == "CodeFirstDatabase.SWBanner")
            {
                return GetView54();
            }

            if (extentName == "CodeFirstDatabase.SWorkerPage")
            {
                return GetView55();
            }

            if (extentName == "ContextDb.SWBanner")
            {
                return GetView56();
            }

            if (extentName == "ContextDb.SWorkerPage")
            {
                return GetView57();
            }

            if (extentName == "CodeFirstDatabase.SWorkerProfile")
            {
                return GetView58();
            }

            if (extentName == "ContextDb.SWorkerProfiles")
            {
                return GetView59();
            }

            if (extentName == "CodeFirstDatabase.UserLocation")
            {
                return GetView60();
            }

            if (extentName == "ContextDb.UserLocations")
            {
                return GetView61();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.AboutPage.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing AboutPage
        [CodeFirstDatabaseSchema.AboutPage](T1.AboutPage_Id, T1.AboutPage_Title, T1.AboutPage_Slug, T1.AboutPage_MainTitle, T1.AboutPage_BannerImage, T1.AboutPage_SubTitle, T1.AboutPage_ButtonUrl, T1.AboutPage_Content, T1.AboutPage_IsAboutMetaDataOn, T1.AboutPage_MetaKeywordse, T1.AboutPage_MetaDescription, T1.AboutPage_IsVisibleToSearchEngine, T1.AboutPage_SectoinId, T1.AboutPage_ShortSectionId)
    FROM (
        SELECT 
            T.Id AS AboutPage_Id, 
            T.Title AS AboutPage_Title, 
            T.Slug AS AboutPage_Slug, 
            T.MainTitle AS AboutPage_MainTitle, 
            T.BannerImage AS AboutPage_BannerImage, 
            T.SubTitle AS AboutPage_SubTitle, 
            T.ButtonUrl AS AboutPage_ButtonUrl, 
            T.Content AS AboutPage_Content, 
            T.IsAboutMetaDataOn AS AboutPage_IsAboutMetaDataOn, 
            T.MetaKeywordse AS AboutPage_MetaKeywordse, 
            T.MetaDescription AS AboutPage_MetaDescription, 
            T.IsVisibleToSearchEngine AS AboutPage_IsVisibleToSearchEngine, 
            T.SectoinId AS AboutPage_SectoinId, 
            T.ShortSectionId AS AboutPage_ShortSectionId, 
            True AS _from0
        FROM ContextDb.AboutPages AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.AboutSection.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing AboutSection
        [CodeFirstDatabaseSchema.AboutSection](T1.AboutSection_Id, T1.AboutSection_Title, T1.AboutSection_MainTitle, T1.AboutSection_SubTitle, T1.AboutSection_Content, T1.AboutSection_ButtonUrl, T1.AboutSection_UrlImages, T1.AboutSection_PublishDateTime)
    FROM (
        SELECT 
            T.Id AS AboutSection_Id, 
            T.Title AS AboutSection_Title, 
            T.MainTitle AS AboutSection_MainTitle, 
            T.SubTitle AS AboutSection_SubTitle, 
            T.Content AS AboutSection_Content, 
            T.ButtonUrl AS AboutSection_ButtonUrl, 
            T.UrlImages AS AboutSection_UrlImages, 
            T.PublishDateTime AS AboutSection_PublishDateTime, 
            True AS _from0
        FROM ContextDb.AboutSections AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.AboutShortSection.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing AboutShortSection
        [CodeFirstDatabaseSchema.AboutShortSection](T1.AboutShortSection_Id, T1.AboutShortSection_Title, T1.AboutShortSection_SubTitle, T1.AboutShortSection_MainTitle, T1.AboutShortSection_Content, T1.AboutShortSection_SubContent, T1.AboutShortSection_PublishDateTime)
    FROM (
        SELECT 
            T.Id AS AboutShortSection_Id, 
            T.Title AS AboutShortSection_Title, 
            T.SubTitle AS AboutShortSection_SubTitle, 
            T.MainTitle AS AboutShortSection_MainTitle, 
            T.Content AS AboutShortSection_Content, 
            T.SubContent AS AboutShortSection_SubContent, 
            T.PublishDateTime AS AboutShortSection_PublishDateTime, 
            True AS _from0
        FROM ContextDb.AboutShortSections AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.AboutPages.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing AboutPages
        [OPMS.Data.Context.AboutPage](T1.AboutPage_Id, T1.AboutPage_Title, T1.AboutPage_Slug, T1.AboutPage_MainTitle, T1.AboutPage_BannerImage, T1.AboutPage_SubTitle, T1.AboutPage_ButtonUrl, T1.AboutPage_Content, T1.AboutPage_IsAboutMetaDataOn, T1.AboutPage_MetaKeywordse, T1.AboutPage_MetaDescription, T1.AboutPage_IsVisibleToSearchEngine, T1.AboutPage_SectoinId, T1.AboutPage_ShortSectionId)
    FROM (
        SELECT 
            T.Id AS AboutPage_Id, 
            T.Title AS AboutPage_Title, 
            T.Slug AS AboutPage_Slug, 
            T.MainTitle AS AboutPage_MainTitle, 
            T.BannerImage AS AboutPage_BannerImage, 
            T.SubTitle AS AboutPage_SubTitle, 
            T.ButtonUrl AS AboutPage_ButtonUrl, 
            T.Content AS AboutPage_Content, 
            T.IsAboutMetaDataOn AS AboutPage_IsAboutMetaDataOn, 
            T.MetaKeywordse AS AboutPage_MetaKeywordse, 
            T.MetaDescription AS AboutPage_MetaDescription, 
            T.IsVisibleToSearchEngine AS AboutPage_IsVisibleToSearchEngine, 
            T.SectoinId AS AboutPage_SectoinId, 
            T.ShortSectionId AS AboutPage_ShortSectionId, 
            True AS _from0
        FROM CodeFirstDatabase.AboutPage AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.AboutSections.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing AboutSections
        [OPMS.Data.Context.AboutSection](T1.AboutSection_Id, T1.AboutSection_Title, T1.AboutSection_MainTitle, T1.AboutSection_SubTitle, T1.AboutSection_Content, T1.AboutSection_ButtonUrl, T1.AboutSection_UrlImages, T1.AboutSection_PublishDateTime)
    FROM (
        SELECT 
            T.Id AS AboutSection_Id, 
            T.Title AS AboutSection_Title, 
            T.MainTitle AS AboutSection_MainTitle, 
            T.SubTitle AS AboutSection_SubTitle, 
            T.Content AS AboutSection_Content, 
            T.ButtonUrl AS AboutSection_ButtonUrl, 
            T.UrlImages AS AboutSection_UrlImages, 
            T.PublishDateTime AS AboutSection_PublishDateTime, 
            True AS _from0
        FROM CodeFirstDatabase.AboutSection AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.AboutShortSections.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing AboutShortSections
        [OPMS.Data.Context.AboutShortSection](T1.AboutShortSection_Id, T1.AboutShortSection_Title, T1.AboutShortSection_SubTitle, T1.AboutShortSection_MainTitle, T1.AboutShortSection_Content, T1.AboutShortSection_SubContent, T1.AboutShortSection_PublishDateTime)
    FROM (
        SELECT 
            T.Id AS AboutShortSection_Id, 
            T.Title AS AboutShortSection_Title, 
            T.SubTitle AS AboutShortSection_SubTitle, 
            T.MainTitle AS AboutShortSection_MainTitle, 
            T.Content AS AboutShortSection_Content, 
            T.SubContent AS AboutShortSection_SubContent, 
            T.PublishDateTime AS AboutShortSection_PublishDateTime, 
            True AS _from0
        FROM CodeFirstDatabase.AboutShortSection AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.AdminActivity.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing AdminActivity
        [CodeFirstDatabaseSchema.AdminActivity](T1.AdminActivity_Id, T1.AdminActivity_Ip, T1.AdminActivity_UserAgint, T1.AdminActivity_ActionName, T1.AdminActivity_ControllerName, T1.AdminActivity_LoginUser, T1.AdminActivity_UserBrowser, T1.AdminActivity_DateTime, T1.AdminActivity_DeviceName, T1.AdminActivity_AuthenticationActivity)
    FROM (
        SELECT 
            T.Id AS AdminActivity_Id, 
            T.Ip AS AdminActivity_Ip, 
            T.UserAgint AS AdminActivity_UserAgint, 
            T.ActionName AS AdminActivity_ActionName, 
            T.ControllerName AS AdminActivity_ControllerName, 
            T.LoginUser AS AdminActivity_LoginUser, 
            T.UserBrowser AS AdminActivity_UserBrowser, 
            T.DateTime AS AdminActivity_DateTime, 
            T.DeviceName AS AdminActivity_DeviceName, 
            T.AuthenticationActivity AS AdminActivity_AuthenticationActivity, 
            True AS _from0
        FROM ContextDb.AdminActivities AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.AdminActivities.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing AdminActivities
        [OPMS.Data.Context.AdminActivity](T1.AdminActivity_Id, T1.AdminActivity_Ip, T1.AdminActivity_UserAgint, T1.AdminActivity_ActionName, T1.AdminActivity_ControllerName, T1.AdminActivity_LoginUser, T1.AdminActivity_UserBrowser, T1.AdminActivity_DateTime, T1.AdminActivity_DeviceName, T1.AdminActivity_AuthenticationActivity)
    FROM (
        SELECT 
            T.Id AS AdminActivity_Id, 
            T.Ip AS AdminActivity_Ip, 
            T.UserAgint AS AdminActivity_UserAgint, 
            T.ActionName AS AdminActivity_ActionName, 
            T.ControllerName AS AdminActivity_ControllerName, 
            T.LoginUser AS AdminActivity_LoginUser, 
            T.UserBrowser AS AdminActivity_UserBrowser, 
            T.DateTime AS AdminActivity_DateTime, 
            T.DeviceName AS AdminActivity_DeviceName, 
            T.AuthenticationActivity AS AdminActivity_AuthenticationActivity, 
            True AS _from0
        FROM CodeFirstDatabase.AdminActivity AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.AdminstratorPanel.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing AdminstratorPanel
        [CodeFirstDatabaseSchema.AdminstratorPanel](T1.AdminstratorPanel_Id, T1.AdminstratorPanel_Title, T1.AdminstratorPanel_Content, T1.AdminstratorPanel_SubContent, T1.AdminstratorPanel_AuthenticatedUser, T1.AdminstratorPanel_ImageUrl)
    FROM (
        SELECT 
            T.Id AS AdminstratorPanel_Id, 
            T.Title AS AdminstratorPanel_Title, 
            T.Content AS AdminstratorPanel_Content, 
            T.SubContent AS AdminstratorPanel_SubContent, 
            T.AuthenticatedUser AS AdminstratorPanel_AuthenticatedUser, 
            T.ImageUrl AS AdminstratorPanel_ImageUrl, 
            True AS _from0
        FROM ContextDb.AdminstratorPanels AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.AdminstratorPanels.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing AdminstratorPanels
        [OPMS.Data.Context.AdminstratorPanel](T1.AdminstratorPanel_Id, T1.AdminstratorPanel_Title, T1.AdminstratorPanel_Content, T1.AdminstratorPanel_SubContent, T1.AdminstratorPanel_AuthenticatedUser, T1.AdminstratorPanel_ImageUrl)
    FROM (
        SELECT 
            T.Id AS AdminstratorPanel_Id, 
            T.Title AS AdminstratorPanel_Title, 
            T.Content AS AdminstratorPanel_Content, 
            T.SubContent AS AdminstratorPanel_SubContent, 
            T.AuthenticatedUser AS AdminstratorPanel_AuthenticatedUser, 
            T.ImageUrl AS AdminstratorPanel_ImageUrl, 
            True AS _from0
        FROM CodeFirstDatabase.AdminstratorPanel AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.ContactDetails.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ContactDetails
        [CodeFirstDatabaseSchema.ContactDetails](T1.ContactDetails_Id, T1.ContactDetails_Title, T1.ContactDetails_CityName, T1.ContactDetails_AreaName, T1.ContactDetails_StreetName, T1.ContactDetails_GoogleAPIMap, T1.ContactDetails_CenterName, T1.ContactDetails_CenterEmail, T1.ContactDetails_MobileNumber)
    FROM (
        SELECT 
            T.Id AS ContactDetails_Id, 
            T.Title AS ContactDetails_Title, 
            T.CityName AS ContactDetails_CityName, 
            T.AreaName AS ContactDetails_AreaName, 
            T.StreetName AS ContactDetails_StreetName, 
            T.GoogleAPIMap AS ContactDetails_GoogleAPIMap, 
            T.CenterName AS ContactDetails_CenterName, 
            T.CenterEmail AS ContactDetails_CenterEmail, 
            T.MobileNumber AS ContactDetails_MobileNumber, 
            True AS _from0
        FROM ContextDb.ContactDetails AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.ContactInfo.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ContactInfo
        [CodeFirstDatabaseSchema.ContactInfo](T1.ContactInfo_Id, T1.ContactInfo_Title, T1.ContactInfo_Content, T1.ContactInfo_PlaceName, T1.ContactInfo_PlaceAddress, T1.ContactInfo_PlaceContactNumber, T1.ContactInfo_WebSite, T1.ContactInfo_PostalCode, T1.ContactInfo_GoogleMap)
    FROM (
        SELECT 
            T.Id AS ContactInfo_Id, 
            T.Title AS ContactInfo_Title, 
            T.Content AS ContactInfo_Content, 
            T.PlaceName AS ContactInfo_PlaceName, 
            T.PlaceAddress AS ContactInfo_PlaceAddress, 
            T.PlaceContactNumber AS ContactInfo_PlaceContactNumber, 
            T.WebSite AS ContactInfo_WebSite, 
            T.PostalCode AS ContactInfo_PostalCode, 
            T.GoogleMap AS ContactInfo_GoogleMap, 
            True AS _from0
        FROM ContextDb.ContactInfos AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.ContactMainPage.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ContactMainPage
        [CodeFirstDatabaseSchema.ContactMainPage](T1.ContactMainPage_Id, T1.ContactMainPage_Title, T1.ContactMainPage_Slug, T1.ContactMainPage_Content, T1.ContactMainPage_SubContent, T1.ContactMainPage_Description, T1.ContactMainPage_ImageUrl, T1.ContactMainPage_GoogleMapAPIUrl, T1.ContactMainPage_IsContactMetaDataOn, T1.ContactMainPage_MetaKeywordse, T1.ContactMainPage_MetaDescription, T1.ContactMainPage_IsVisibleToSearchEngine, T1.ContactMainPage_ContactDetailsId, T1.ContactMainPage_ContactInfoId, T1.ContactMainPage_ContactFormId)
    FROM (
        SELECT 
            T.Id AS ContactMainPage_Id, 
            T.Title AS ContactMainPage_Title, 
            T.Slug AS ContactMainPage_Slug, 
            T.Content AS ContactMainPage_Content, 
            T.SubContent AS ContactMainPage_SubContent, 
            T.Description AS ContactMainPage_Description, 
            T.ImageUrl AS ContactMainPage_ImageUrl, 
            T.GoogleMapAPIUrl AS ContactMainPage_GoogleMapAPIUrl, 
            T.IsContactMetaDataOn AS ContactMainPage_IsContactMetaDataOn, 
            T.MetaKeywordse AS ContactMainPage_MetaKeywordse, 
            T.MetaDescription AS ContactMainPage_MetaDescription, 
            T.IsVisibleToSearchEngine AS ContactMainPage_IsVisibleToSearchEngine, 
            T.ContactDetailsId AS ContactMainPage_ContactDetailsId, 
            T.ContactInfoId AS ContactMainPage_ContactInfoId, 
            T.ContactFormId AS ContactMainPage_ContactFormId, 
            True AS _from0
        FROM ContextDb.ContactPages AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Contact.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Contact
        [CodeFirstDatabaseSchema.Contact](T1.Contact_Id, T1.Contact_FullName, T1.Contact_Email, T1.Contact_Address, T1.Contact_MobileNumber, T1.Contact_IpAddres, T1.Contact_ContactedDate, T1.Contact_MessageText, T1.Contact_ContactedLocation)
    FROM (
        SELECT 
            T.Id AS Contact_Id, 
            T.FullName AS Contact_FullName, 
            T.Email AS Contact_Email, 
            T.Address AS Contact_Address, 
            T.MobileNumber AS Contact_MobileNumber, 
            T.IpAddres AS Contact_IpAddres, 
            T.ContactedDate AS Contact_ContactedDate, 
            T.MessageText AS Contact_MessageText, 
            T.ContactedLocation AS Contact_ContactedLocation, 
            True AS _from0
        FROM ContextDb.Contacts AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.ContactDetails.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView14()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ContactDetails
        [OPMS.Data.Context.ContactDetails](T1.ContactDetails_Id, T1.ContactDetails_Title, T1.ContactDetails_CityName, T1.ContactDetails_AreaName, T1.ContactDetails_StreetName, T1.ContactDetails_GoogleAPIMap, T1.ContactDetails_CenterName, T1.ContactDetails_CenterEmail, T1.ContactDetails_MobileNumber)
    FROM (
        SELECT 
            T.Id AS ContactDetails_Id, 
            T.Title AS ContactDetails_Title, 
            T.CityName AS ContactDetails_CityName, 
            T.AreaName AS ContactDetails_AreaName, 
            T.StreetName AS ContactDetails_StreetName, 
            T.GoogleAPIMap AS ContactDetails_GoogleAPIMap, 
            T.CenterName AS ContactDetails_CenterName, 
            T.CenterEmail AS ContactDetails_CenterEmail, 
            T.MobileNumber AS ContactDetails_MobileNumber, 
            True AS _from0
        FROM CodeFirstDatabase.ContactDetails AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.ContactInfos.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView15()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ContactInfos
        [OPMS.Data.Context.ContactInfo](T1.ContactInfo_Id, T1.ContactInfo_Title, T1.ContactInfo_Content, T1.ContactInfo_PlaceName, T1.ContactInfo_PlaceAddress, T1.ContactInfo_PlaceContactNumber, T1.ContactInfo_WebSite, T1.ContactInfo_PostalCode, T1.ContactInfo_GoogleMap)
    FROM (
        SELECT 
            T.Id AS ContactInfo_Id, 
            T.Title AS ContactInfo_Title, 
            T.Content AS ContactInfo_Content, 
            T.PlaceName AS ContactInfo_PlaceName, 
            T.PlaceAddress AS ContactInfo_PlaceAddress, 
            T.PlaceContactNumber AS ContactInfo_PlaceContactNumber, 
            T.WebSite AS ContactInfo_WebSite, 
            T.PostalCode AS ContactInfo_PostalCode, 
            T.GoogleMap AS ContactInfo_GoogleMap, 
            True AS _from0
        FROM CodeFirstDatabase.ContactInfo AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.ContactPages.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView16()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ContactPages
        [OPMS.Data.Context.ContactMainPage](T1.ContactMainPage_Id, T1.ContactMainPage_Title, T1.ContactMainPage_Slug, T1.ContactMainPage_Content, T1.ContactMainPage_SubContent, T1.ContactMainPage_Description, T1.ContactMainPage_ImageUrl, T1.ContactMainPage_GoogleMapAPIUrl, T1.ContactMainPage_IsContactMetaDataOn, T1.ContactMainPage_MetaKeywordse, T1.ContactMainPage_MetaDescription, T1.ContactMainPage_IsVisibleToSearchEngine, T1.ContactMainPage_ContactDetailsId, T1.ContactMainPage_ContactInfoId, T1.ContactMainPage_ContactFormId)
    FROM (
        SELECT 
            T.Id AS ContactMainPage_Id, 
            T.Title AS ContactMainPage_Title, 
            T.Slug AS ContactMainPage_Slug, 
            T.Content AS ContactMainPage_Content, 
            T.SubContent AS ContactMainPage_SubContent, 
            T.Description AS ContactMainPage_Description, 
            T.ImageUrl AS ContactMainPage_ImageUrl, 
            T.GoogleMapAPIUrl AS ContactMainPage_GoogleMapAPIUrl, 
            T.IsContactMetaDataOn AS ContactMainPage_IsContactMetaDataOn, 
            T.MetaKeywordse AS ContactMainPage_MetaKeywordse, 
            T.MetaDescription AS ContactMainPage_MetaDescription, 
            T.IsVisibleToSearchEngine AS ContactMainPage_IsVisibleToSearchEngine, 
            T.ContactDetailsId AS ContactMainPage_ContactDetailsId, 
            T.ContactInfoId AS ContactMainPage_ContactInfoId, 
            T.ContactFormId AS ContactMainPage_ContactFormId, 
            True AS _from0
        FROM CodeFirstDatabase.ContactMainPage AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.Contacts.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView17()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Contacts
        [OPMS.Data.Context.Contact](T1.Contact_Id, T1.Contact_FullName, T1.Contact_Email, T1.Contact_Address, T1.Contact_MobileNumber, T1.Contact_IpAddres, T1.Contact_ContactedDate, T1.Contact_MessageText, T1.Contact_ContactedLocation)
    FROM (
        SELECT 
            T.Id AS Contact_Id, 
            T.FullName AS Contact_FullName, 
            T.Email AS Contact_Email, 
            T.Address AS Contact_Address, 
            T.MobileNumber AS Contact_MobileNumber, 
            T.IpAddres AS Contact_IpAddres, 
            T.ContactedDate AS Contact_ContactedDate, 
            T.MessageText AS Contact_MessageText, 
            T.ContactedLocation AS Contact_ContactedLocation, 
            True AS _from0
        FROM CodeFirstDatabase.Contact AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.HelpSupport.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView18()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HelpSupport
        [CodeFirstDatabaseSchema.HelpSupport](T1.HelpSupport_Id, T1.HelpSupport_Title, T1.HelpSupport_CompanyName, T1.HelpSupport_Content, T1.HelpSupport_DeveloperName, T1.HelpSupport_SoftwareDownload, T1.HelpSupport_ProiflePic, T1.HelpSupport_DesignedBy, T1.HelpSupport_CreatedDate, T1.HelpSupport_Email, T1.HelpSupport_Skype)
    FROM (
        SELECT 
            T.Id AS HelpSupport_Id, 
            T.Title AS HelpSupport_Title, 
            T.CompanyName AS HelpSupport_CompanyName, 
            T.Content AS HelpSupport_Content, 
            T.DeveloperName AS HelpSupport_DeveloperName, 
            T.SoftwareDownload AS HelpSupport_SoftwareDownload, 
            T.ProiflePic AS HelpSupport_ProiflePic, 
            T.DesignedBy AS HelpSupport_DesignedBy, 
            T.CreatedDate AS HelpSupport_CreatedDate, 
            T.Email AS HelpSupport_Email, 
            T.Skype AS HelpSupport_Skype, 
            True AS _from0
        FROM ContextDb.HelpSupports AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.HelpSupports.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView19()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HelpSupports
        [OPMS.Data.Context.HelpSupport](T1.HelpSupport_Id, T1.HelpSupport_Title, T1.HelpSupport_CompanyName, T1.HelpSupport_Content, T1.HelpSupport_DeveloperName, T1.HelpSupport_SoftwareDownload, T1.HelpSupport_ProiflePic, T1.HelpSupport_DesignedBy, T1.HelpSupport_CreatedDate, T1.HelpSupport_Email, T1.HelpSupport_Skype)
    FROM (
        SELECT 
            T.Id AS HelpSupport_Id, 
            T.Title AS HelpSupport_Title, 
            T.CompanyName AS HelpSupport_CompanyName, 
            T.Content AS HelpSupport_Content, 
            T.DeveloperName AS HelpSupport_DeveloperName, 
            T.SoftwareDownload AS HelpSupport_SoftwareDownload, 
            T.ProiflePic AS HelpSupport_ProiflePic, 
            T.DesignedBy AS HelpSupport_DesignedBy, 
            T.CreatedDate AS HelpSupport_CreatedDate, 
            T.Email AS HelpSupport_Email, 
            T.Skype AS HelpSupport_Skype, 
            True AS _from0
        FROM CodeFirstDatabase.HelpSupport AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.HomeBanner.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView20()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HomeBanner
        [CodeFirstDatabaseSchema.HomeBanner](T1.HomeBanner_Id, T1.HomeBanner_Title, T1.HomeBanner_SubTitle, T1.HomeBanner_ImageUrl, T1.HomeBanner_ButtonText, T1.HomeBanner_ButtonUrl, T1.HomeBanner_Content)
    FROM (
        SELECT 
            T.Id AS HomeBanner_Id, 
            T.Title AS HomeBanner_Title, 
            T.SubTitle AS HomeBanner_SubTitle, 
            T.ImageUrl AS HomeBanner_ImageUrl, 
            T.ButtonText AS HomeBanner_ButtonText, 
            T.ButtonUrl AS HomeBanner_ButtonUrl, 
            T.Content AS HomeBanner_Content, 
            True AS _from0
        FROM ContextDb.HomeBanners AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Page.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView21()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Page
        [CodeFirstDatabaseSchema.Page](T1.Page_Id, T1.Page_Title, T1.Page_Slug, T1.Page_Content, T1.Page_IsPageMetaDataOn, T1.Page_MetaKeywordse, T1.Page_MetaDescription, T1.Page_IsVisibleToSearchEngine, T1.Page_SidebarId, T1.Page_BannerId, T1.Page_HomeContentId)
    FROM (
        SELECT 
            T.Id AS Page_Id, 
            T.Title AS Page_Title, 
            T.Slug AS Page_Slug, 
            T.Content AS Page_Content, 
            T.IsPageMetaDataOn AS Page_IsPageMetaDataOn, 
            T.MetaKeywordse AS Page_MetaKeywordse, 
            T.MetaDescription AS Page_MetaDescription, 
            T.IsVisibleToSearchEngine AS Page_IsVisibleToSearchEngine, 
            T.SidebarId AS Page_SidebarId, 
            T.BannerId AS Page_BannerId, 
            T.HomeContentId AS Page_HomeContentId, 
            True AS _from0
        FROM ContextDb.Pages AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.HomeContent.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView22()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HomeContent
        [CodeFirstDatabaseSchema.HomeContent](T1.HomeContent_Id, T1.HomeContent_Title, T1.HomeContent_SubTitle, T1.HomeContent_Content, T1.HomeContent_SubContent, T1.HomeContent_ButtonText, T1.HomeContent_ButtonUrl, T1.HomeContent_ImageUrl)
    FROM (
        SELECT 
            T.Id AS HomeContent_Id, 
            T.Title AS HomeContent_Title, 
            T.SubTitle AS HomeContent_SubTitle, 
            T.Content AS HomeContent_Content, 
            T.SubContent AS HomeContent_SubContent, 
            T.ButtonText AS HomeContent_ButtonText, 
            T.ButtonUrl AS HomeContent_ButtonUrl, 
            T.ImageUrl AS HomeContent_ImageUrl, 
            True AS _from0
        FROM ContextDb.HomeContents AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Sidebar.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView23()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Sidebar
        [CodeFirstDatabaseSchema.Sidebar](T1.Sidebar_Id, T1.Sidebar_Name, T1.Sidebar_Content, T1.Sidebar_PublishDate)
    FROM (
        SELECT 
            T.Id AS Sidebar_Id, 
            T.Name AS Sidebar_Name, 
            T.Content AS Sidebar_Content, 
            T.PublishDate AS Sidebar_PublishDate, 
            True AS _from0
        FROM ContextDb.Sidebars AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.HomeBanners.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView24()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HomeBanners
        [OPMS.Data.Context.HomeBanner](T1.HomeBanner_Id, T1.HomeBanner_Title, T1.HomeBanner_SubTitle, T1.HomeBanner_ImageUrl, T1.HomeBanner_ButtonText, T1.HomeBanner_ButtonUrl, T1.HomeBanner_Content)
    FROM (
        SELECT 
            T.Id AS HomeBanner_Id, 
            T.Title AS HomeBanner_Title, 
            T.SubTitle AS HomeBanner_SubTitle, 
            T.ImageUrl AS HomeBanner_ImageUrl, 
            T.ButtonText AS HomeBanner_ButtonText, 
            T.ButtonUrl AS HomeBanner_ButtonUrl, 
            T.Content AS HomeBanner_Content, 
            True AS _from0
        FROM CodeFirstDatabase.HomeBanner AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.Pages.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView25()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Pages
        [OPMS.Data.Context.Page](T1.Page_Id, T1.Page_Title, T1.Page_Slug, T1.Page_Content, T1.Page_IsPageMetaDataOn, T1.Page_MetaKeywordse, T1.Page_MetaDescription, T1.Page_IsVisibleToSearchEngine, T1.Page_SidebarId, T1.Page_BannerId, T1.Page_HomeContentId)
    FROM (
        SELECT 
            T.Id AS Page_Id, 
            T.Title AS Page_Title, 
            T.Slug AS Page_Slug, 
            T.Content AS Page_Content, 
            T.IsPageMetaDataOn AS Page_IsPageMetaDataOn, 
            T.MetaKeywordse AS Page_MetaKeywordse, 
            T.MetaDescription AS Page_MetaDescription, 
            T.IsVisibleToSearchEngine AS Page_IsVisibleToSearchEngine, 
            T.SidebarId AS Page_SidebarId, 
            T.BannerId AS Page_BannerId, 
            T.HomeContentId AS Page_HomeContentId, 
            True AS _from0
        FROM CodeFirstDatabase.Page AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.HomeContents.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView26()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HomeContents
        [OPMS.Data.Context.HomeContent](T1.HomeContent_Id, T1.HomeContent_Title, T1.HomeContent_SubTitle, T1.HomeContent_Content, T1.HomeContent_SubContent, T1.HomeContent_ButtonText, T1.HomeContent_ButtonUrl, T1.HomeContent_ImageUrl)
    FROM (
        SELECT 
            T.Id AS HomeContent_Id, 
            T.Title AS HomeContent_Title, 
            T.SubTitle AS HomeContent_SubTitle, 
            T.Content AS HomeContent_Content, 
            T.SubContent AS HomeContent_SubContent, 
            T.ButtonText AS HomeContent_ButtonText, 
            T.ButtonUrl AS HomeContent_ButtonUrl, 
            T.ImageUrl AS HomeContent_ImageUrl, 
            True AS _from0
        FROM CodeFirstDatabase.HomeContent AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.Sidebars.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView27()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Sidebars
        [OPMS.Data.Context.Sidebar](T1.Sidebar_Id, T1.Sidebar_Name, T1.Sidebar_Content, T1.Sidebar_PublishDate)
    FROM (
        SELECT 
            T.Id AS Sidebar_Id, 
            T.Name AS Sidebar_Name, 
            T.Content AS Sidebar_Content, 
            T.PublishDate AS Sidebar_PublishDate, 
            True AS _from0
        FROM CodeFirstDatabase.Sidebar AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.HomeRR.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView28()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HomeRR
        [CodeFirstDatabaseSchema.HomeRR](T1.HomeRR_Id, T1.HomeRR_Title, T1.HomeRR_Content, T1.HomeRR_IconUrl)
    FROM (
        SELECT 
            T.Id AS HomeRR_Id, 
            T.Title AS HomeRR_Title, 
            T.Content AS HomeRR_Content, 
            T.IconUrl AS HomeRR_IconUrl, 
            True AS _from0
        FROM ContextDb.HomeRolesResponsibilities AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.HomeRolesResponsibilities.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView29()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HomeRolesResponsibilities
        [OPMS.Data.Context.HomeRR](T1.HomeRR_Id, T1.HomeRR_Title, T1.HomeRR_Content, T1.HomeRR_IconUrl)
    FROM (
        SELECT 
            T.Id AS HomeRR_Id, 
            T.Title AS HomeRR_Title, 
            T.Content AS HomeRR_Content, 
            T.IconUrl AS HomeRR_IconUrl, 
            True AS _from0
        FROM CodeFirstDatabase.HomeRR AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.MainPostSystem.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView30()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MainPostSystem
        [CodeFirstDatabaseSchema.MainPostSystem](T1.MainPostSystem_Id, T1.MainPostSystem_Title, T1.MainPostSystem_SentDateTime, T1.MainPostSystem_PostExpirationDate, T1.MainPostSystem_SendedBy, T1.MainPostSystem_HasPost, T1.MainPostSystem_UserId, T1.MainPostSystem_Name, T1.MainPostSystem_PostSystemId, T1.MainPostSystem_SocialId)
    FROM (
        SELECT 
            T.Id AS MainPostSystem_Id, 
            T.Title AS MainPostSystem_Title, 
            T.SentDateTime AS MainPostSystem_SentDateTime, 
            T.PostExpirationDate AS MainPostSystem_PostExpirationDate, 
            T.SendedBy AS MainPostSystem_SendedBy, 
            T.HasPost AS MainPostSystem_HasPost, 
            T.UserId AS MainPostSystem_UserId, 
            T.Name AS MainPostSystem_Name, 
            T.PostSystemId AS MainPostSystem_PostSystemId, 
            T.SocialId AS MainPostSystem_SocialId, 
            True AS _from0
        FROM ContextDb.MainPostSystems AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.PostSystem.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView31()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PostSystem
        [CodeFirstDatabaseSchema.PostSystem](T1.PostSystem_Id, T1.PostSystem_Title, T1.PostSystem_SubTitle, T1.PostSystem_Content, T1.PostSystem_PostCreatedBy)
    FROM (
        SELECT 
            T.Id AS PostSystem_Id, 
            T.Title AS PostSystem_Title, 
            T.SubTitle AS PostSystem_SubTitle, 
            T.Content AS PostSystem_Content, 
            T.PostCreatedBy AS PostSystem_PostCreatedBy, 
            True AS _from0
        FROM ContextDb.PostSystems AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.SocialWorker.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView32()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SocialWorker
        [CodeFirstDatabaseSchema.SocialWorker](T1.SocialWorker_Id, T1.SocialWorker_FullName, T1.SocialWorker_Position)
    FROM (
        SELECT 
            T.Id AS SocialWorker_Id, 
            T.FullName AS SocialWorker_FullName, 
            T.Position AS SocialWorker_Position, 
            True AS _from0
        FROM ContextDb.SocialWorkers AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.UserModel.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView33()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserModel
        [CodeFirstDatabaseSchema.UserModel](T1.UserModel_Id, T1.UserModel_UserName, T1.UserModel_PhoneNumber, T1.UserModel_Email, T1.UserModel_HashPassword)
    FROM (
        SELECT 
            T.Id AS UserModel_Id, 
            T.UserName AS UserModel_UserName, 
            T.PhoneNumber AS UserModel_PhoneNumber, 
            T.Email AS UserModel_Email, 
            T.HashPassword AS UserModel_HashPassword, 
            True AS _from0
        FROM ContextDb.Users AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.RoleModel.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView34()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing RoleModel
        [CodeFirstDatabaseSchema.RoleModel](T1.RoleModel_Id, T1.RoleModel_Name)
    FROM (
        SELECT 
            T.Id AS RoleModel_Id, 
            T.Name AS RoleModel_Name, 
            True AS _from0
        FROM ContextDb.Roles AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.MessageContainer.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView35()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MessageContainer
        [CodeFirstDatabaseSchema.MessageContainer](T1.MessageContainer_Id, T1.MessageContainer_Title, T1.MessageContainer_SubTitle, T1.MessageContainer_Content, T1.MessageContainer_CreatedBy)
    FROM (
        SELECT 
            T.Id AS MessageContainer_Id, 
            T.Title AS MessageContainer_Title, 
            T.SubTitle AS MessageContainer_SubTitle, 
            T.Content AS MessageContainer_Content, 
            T.CreatedBy AS MessageContainer_CreatedBy, 
            True AS _from0
        FROM ContextDb.MessageContainers AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Messages.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView36()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Messages
        [CodeFirstDatabaseSchema.Messages](T1.Messages_Id, T1.Messages_Title, T1.Messages_SentDateTime, T1.Messages_AppointmentOrTaskDateTime, T1.Messages_SendedBy, T1.Messages_UserId, T1.Messages_MessageContainerId, T1.Messages_SocialId)
    FROM (
        SELECT 
            T.Id AS Messages_Id, 
            T.Title AS Messages_Title, 
            T.SentDateTime AS Messages_SentDateTime, 
            T.AppointmentOrTaskDateTime AS Messages_AppointmentOrTaskDateTime, 
            T.SendedBy AS Messages_SendedBy, 
            T.UserId AS Messages_UserId, 
            T.MessageContainerId AS Messages_MessageContainerId, 
            T.SocialId AS Messages_SocialId, 
            True AS _from0
        FROM ContextDb.Messages AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.UserModelRoleModel.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView37()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserModelRoleModel
        [CodeFirstDatabaseSchema.UserModelRoleModel](T1.UserModelRoleModel_UserId, T1.UserModelRoleModel_RoleId)
    FROM (
        SELECT 
            Key(T.UserModel_Roles_Source).Id AS UserModelRoleModel_UserId, 
            Key(T.UserModel_Roles_Target).Id AS UserModelRoleModel_RoleId, 
            True AS _from0
        FROM ContextDb.UserModel_Roles AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.MainPostSystems.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView38()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MainPostSystems
        [OPMS.Data.Context.MainPostSystem](T1.MainPostSystem_Id, T1.MainPostSystem_Title, T1.MainPostSystem_SentDateTime, T1.MainPostSystem_PostExpirationDate, T1.MainPostSystem_SendedBy, T1.MainPostSystem_HasPost, T1.MainPostSystem_UserId, T1.MainPostSystem_Name, T1.MainPostSystem_PostSystemId, T1.MainPostSystem_SocialId)
    FROM (
        SELECT 
            T.Id AS MainPostSystem_Id, 
            T.Title AS MainPostSystem_Title, 
            T.SentDateTime AS MainPostSystem_SentDateTime, 
            T.PostExpirationDate AS MainPostSystem_PostExpirationDate, 
            T.SendedBy AS MainPostSystem_SendedBy, 
            T.HasPost AS MainPostSystem_HasPost, 
            T.UserId AS MainPostSystem_UserId, 
            T.Name AS MainPostSystem_Name, 
            T.PostSystemId AS MainPostSystem_PostSystemId, 
            T.SocialId AS MainPostSystem_SocialId, 
            True AS _from0
        FROM CodeFirstDatabase.MainPostSystem AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.PostSystems.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView39()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing PostSystems
        [OPMS.Data.Context.PostSystem](T1.PostSystem_Id, T1.PostSystem_Title, T1.PostSystem_SubTitle, T1.PostSystem_Content, T1.PostSystem_PostCreatedBy)
    FROM (
        SELECT 
            T.Id AS PostSystem_Id, 
            T.Title AS PostSystem_Title, 
            T.SubTitle AS PostSystem_SubTitle, 
            T.Content AS PostSystem_Content, 
            T.PostCreatedBy AS PostSystem_PostCreatedBy, 
            True AS _from0
        FROM CodeFirstDatabase.PostSystem AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.SocialWorkers.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView40()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SocialWorkers
        [OPMS.Data.Context.SocialWorker](T1.SocialWorker_Id, T1.SocialWorker_FullName, T1.SocialWorker_Position)
    FROM (
        SELECT 
            T.Id AS SocialWorker_Id, 
            T.FullName AS SocialWorker_FullName, 
            T.Position AS SocialWorker_Position, 
            True AS _from0
        FROM CodeFirstDatabase.SocialWorker AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.Users.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView41()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Users
        [OPMS.Data.Context.UserModel](T1.UserModel_Id, T1.UserModel_UserName, T1.UserModel_PhoneNumber, T1.UserModel_Email, T1.UserModel_HashPassword)
    FROM (
        SELECT 
            T.Id AS UserModel_Id, 
            T.UserName AS UserModel_UserName, 
            T.PhoneNumber AS UserModel_PhoneNumber, 
            T.Email AS UserModel_Email, 
            T.HashPassword AS UserModel_HashPassword, 
            True AS _from0
        FROM CodeFirstDatabase.UserModel AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.Roles.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView42()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Roles
        [OPMS.Data.Context.RoleModel](T1.RoleModel_Id, T1.RoleModel_Name)
    FROM (
        SELECT 
            T.Id AS RoleModel_Id, 
            T.Name AS RoleModel_Name, 
            True AS _from0
        FROM CodeFirstDatabase.RoleModel AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.MessageContainers.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView43()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MessageContainers
        [OPMS.Data.Context.MessageContainer](T1.MessageContainer_Id, T1.MessageContainer_Title, T1.MessageContainer_SubTitle, T1.MessageContainer_Content, T1.MessageContainer_CreatedBy)
    FROM (
        SELECT 
            T.Id AS MessageContainer_Id, 
            T.Title AS MessageContainer_Title, 
            T.SubTitle AS MessageContainer_SubTitle, 
            T.Content AS MessageContainer_Content, 
            T.CreatedBy AS MessageContainer_CreatedBy, 
            True AS _from0
        FROM CodeFirstDatabase.MessageContainer AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.Messages.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView44()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Messages
        [OPMS.Data.Context.Messages](T1.Messages_Id, T1.Messages_Title, T1.Messages_SentDateTime, T1.Messages_AppointmentOrTaskDateTime, T1.Messages_SendedBy, T1.Messages_UserId, T1.Messages_MessageContainerId, T1.Messages_SocialId)
    FROM (
        SELECT 
            T.Id AS Messages_Id, 
            T.Title AS Messages_Title, 
            T.SentDateTime AS Messages_SentDateTime, 
            T.AppointmentOrTaskDateTime AS Messages_AppointmentOrTaskDateTime, 
            T.SendedBy AS Messages_SendedBy, 
            T.UserId AS Messages_UserId, 
            T.MessageContainerId AS Messages_MessageContainerId, 
            T.SocialId AS Messages_SocialId, 
            True AS _from0
        FROM CodeFirstDatabase.Messages AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.UserModel_Roles.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView45()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserModel_Roles
        [OPMS.Data.Context.UserModel_Roles](T3.[UserModel_Roles.UserModel_Roles_Source], T3.[UserModel_Roles.UserModel_Roles_Target])
    FROM (
        SELECT -- Constructing UserModel_Roles_Source
            CreateRef(ContextDb.Users, row(T2.[UserModel_Roles.UserModel_Roles_Source.Id]), [OPMS.Data.Context.UserModel]) AS [UserModel_Roles.UserModel_Roles_Source], 
            T2.[UserModel_Roles.UserModel_Roles_Target]
        FROM (
            SELECT -- Constructing UserModel_Roles_Target
                T1.[UserModel_Roles.UserModel_Roles_Source.Id], 
                CreateRef(ContextDb.Roles, row(T1.[UserModel_Roles.UserModel_Roles_Target.Id]), [OPMS.Data.Context.RoleModel]) AS [UserModel_Roles.UserModel_Roles_Target]
            FROM (
                SELECT 
                    T.UserId AS [UserModel_Roles.UserModel_Roles_Source.Id], 
                    T.RoleId AS [UserModel_Roles.UserModel_Roles_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.UserModelRoleModel AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Menu.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView46()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Menu
        [CodeFirstDatabaseSchema.Menu](T1.Menu_Id, T1.Menu_Title, T1.Menu_Description, T1.Menu_Url, T1.Menu_ParentId)
    FROM (
        SELECT 
            T.Id AS Menu_Id, 
            T.Title AS Menu_Title, 
            T.Description AS Menu_Description, 
            T.Url AS Menu_Url, 
            T.ParentId AS Menu_ParentId, 
            True AS _from0
        FROM ContextDb.Menus AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.Menus.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView47()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Menus
        [OPMS.Data.Context.Menu](T1.Menu_Id, T1.Menu_Title, T1.Menu_Description, T1.Menu_Url, T1.Menu_ParentId)
    FROM (
        SELECT 
            T.Id AS Menu_Id, 
            T.Title AS Menu_Title, 
            T.Description AS Menu_Description, 
            T.Url AS Menu_Url, 
            T.ParentId AS Menu_ParentId, 
            True AS _from0
        FROM CodeFirstDatabase.Menu AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.NewsBanner.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView48()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing NewsBanner
        [CodeFirstDatabaseSchema.NewsBanner](T1.NewsBanner_Id, T1.NewsBanner_Title, T1.NewsBanner_SubTitle, T1.NewsBanner_ImageUrl, T1.NewsBanner_ButtonText, T1.NewsBanner_ButtonUrl, T1.NewsBanner_Content)
    FROM (
        SELECT 
            T.Id AS NewsBanner_Id, 
            T.Title AS NewsBanner_Title, 
            T.SubTitle AS NewsBanner_SubTitle, 
            T.ImageUrl AS NewsBanner_ImageUrl, 
            T.ButtonText AS NewsBanner_ButtonText, 
            T.ButtonUrl AS NewsBanner_ButtonUrl, 
            T.Content AS NewsBanner_Content, 
            True AS _from0
        FROM ContextDb.NewsBanners AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.NewsInfo.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView49()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing NewsInfo
        [CodeFirstDatabaseSchema.NewsInfo](T1.NewsInfo_Id, T1.NewsInfo_Title, T1.NewsInfo_Content, T1.NewsInfo_ButtonUrl, T1.NewsInfo_ButtonText, T1.NewsInfo_SubContent, T1.NewsInfo_PublishDate, T1.NewsInfo_ImageUrl, T1.NewsInfo_GoogleMapAPIUrl, T1.NewsInfo_IsNewsInfotMetaDataOn, T1.NewsInfo_MetaKeywordse, T1.NewsInfo_MetaDescription, T1.NewsInfo_IsVisibleToSearchEngine, T1.NewsInfo_NewsBannerId)
    FROM (
        SELECT 
            T.Id AS NewsInfo_Id, 
            T.Title AS NewsInfo_Title, 
            T.Content AS NewsInfo_Content, 
            T.ButtonUrl AS NewsInfo_ButtonUrl, 
            T.ButtonText AS NewsInfo_ButtonText, 
            T.SubContent AS NewsInfo_SubContent, 
            T.PublishDate AS NewsInfo_PublishDate, 
            T.ImageUrl AS NewsInfo_ImageUrl, 
            T.GoogleMapAPIUrl AS NewsInfo_GoogleMapAPIUrl, 
            T.IsNewsInfotMetaDataOn AS NewsInfo_IsNewsInfotMetaDataOn, 
            T.MetaKeywordse AS NewsInfo_MetaKeywordse, 
            T.MetaDescription AS NewsInfo_MetaDescription, 
            T.IsVisibleToSearchEngine AS NewsInfo_IsVisibleToSearchEngine, 
            T.NewsBannerId AS NewsInfo_NewsBannerId, 
            True AS _from0
        FROM ContextDb.NewsInfos AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.NewsBanners.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView50()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing NewsBanners
        [OPMS.Data.Context.NewsBanner](T1.NewsBanner_Id, T1.NewsBanner_Title, T1.NewsBanner_SubTitle, T1.NewsBanner_ImageUrl, T1.NewsBanner_ButtonText, T1.NewsBanner_ButtonUrl, T1.NewsBanner_Content)
    FROM (
        SELECT 
            T.Id AS NewsBanner_Id, 
            T.Title AS NewsBanner_Title, 
            T.SubTitle AS NewsBanner_SubTitle, 
            T.ImageUrl AS NewsBanner_ImageUrl, 
            T.ButtonText AS NewsBanner_ButtonText, 
            T.ButtonUrl AS NewsBanner_ButtonUrl, 
            T.Content AS NewsBanner_Content, 
            True AS _from0
        FROM CodeFirstDatabase.NewsBanner AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.NewsInfos.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView51()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing NewsInfos
        [OPMS.Data.Context.NewsInfo](T1.NewsInfo_Id, T1.NewsInfo_Title, T1.NewsInfo_Content, T1.NewsInfo_ButtonUrl, T1.NewsInfo_ButtonText, T1.NewsInfo_SubContent, T1.NewsInfo_PublishDate, T1.NewsInfo_ImageUrl, T1.NewsInfo_GoogleMapAPIUrl, T1.NewsInfo_IsNewsInfotMetaDataOn, T1.NewsInfo_MetaKeywordse, T1.NewsInfo_MetaDescription, T1.NewsInfo_IsVisibleToSearchEngine, T1.NewsInfo_NewsBannerId)
    FROM (
        SELECT 
            T.Id AS NewsInfo_Id, 
            T.Title AS NewsInfo_Title, 
            T.Content AS NewsInfo_Content, 
            T.ButtonUrl AS NewsInfo_ButtonUrl, 
            T.ButtonText AS NewsInfo_ButtonText, 
            T.SubContent AS NewsInfo_SubContent, 
            T.PublishDate AS NewsInfo_PublishDate, 
            T.ImageUrl AS NewsInfo_ImageUrl, 
            T.GoogleMapAPIUrl AS NewsInfo_GoogleMapAPIUrl, 
            T.IsNewsInfotMetaDataOn AS NewsInfo_IsNewsInfotMetaDataOn, 
            T.MetaKeywordse AS NewsInfo_MetaKeywordse, 
            T.MetaDescription AS NewsInfo_MetaDescription, 
            T.IsVisibleToSearchEngine AS NewsInfo_IsVisibleToSearchEngine, 
            T.NewsBannerId AS NewsInfo_NewsBannerId, 
            True AS _from0
        FROM CodeFirstDatabase.NewsInfo AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.SiteSettings.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView52()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SiteSettings
        [CodeFirstDatabaseSchema.SiteSettings](T1.SiteSettings_Id, T1.SiteSettings_SiteName, T1.SiteSettings_IsRegister, T1.SiteSettings_SiteFooter, T1.SiteSettings_FavIconURL, T1.SiteSettings_SiteOwner, T1.SiteSettings_CustomCSS, T1.SiteSettings_GoogleSiteVerification, T1.SiteSettings_GoogelAds, T1.SiteSettings_IsCustomCSSOn, T1.SiteSettings_CustomJS, T1.SiteSettings_IsCustomJsOn, T1.SiteSettings_SiteLastUpdated, T1.SiteSettings_UpdateBy, T1.SiteSettings_HomeFooter, T1.SiteSettings_HomeUrl, T1.SiteSettings_AboutFooter, T1.SiteSettings_AboutUrl, T1.SiteSettings_ContactFooter, T1.SiteSettings_ContactUrl, T1.SiteSettings_RolesFooter, T1.SiteSettings_RolesUrl, T1.SiteSettings_ContactNumberFooter, T1.SiteSettings_EmailFooter, T1.SiteSettings_AddresFooter, T1.SiteSettings_ContentFooter, T1.SiteSettings_CopyrightFooter, T1.SiteSettings_LoginFooter, T1.SiteSettings_LoginUrl)
    FROM (
        SELECT 
            T.Id AS SiteSettings_Id, 
            T.SiteName AS SiteSettings_SiteName, 
            T.IsRegister AS SiteSettings_IsRegister, 
            T.SiteFooter AS SiteSettings_SiteFooter, 
            T.FavIconURL AS SiteSettings_FavIconURL, 
            T.SiteOwner AS SiteSettings_SiteOwner, 
            T.CustomCSS AS SiteSettings_CustomCSS, 
            T.GoogleSiteVerification AS SiteSettings_GoogleSiteVerification, 
            T.GoogelAds AS SiteSettings_GoogelAds, 
            T.IsCustomCSSOn AS SiteSettings_IsCustomCSSOn, 
            T.CustomJS AS SiteSettings_CustomJS, 
            T.IsCustomJsOn AS SiteSettings_IsCustomJsOn, 
            T.SiteLastUpdated AS SiteSettings_SiteLastUpdated, 
            T.UpdateBy AS SiteSettings_UpdateBy, 
            T.HomeFooter AS SiteSettings_HomeFooter, 
            T.HomeUrl AS SiteSettings_HomeUrl, 
            T.AboutFooter AS SiteSettings_AboutFooter, 
            T.AboutUrl AS SiteSettings_AboutUrl, 
            T.ContactFooter AS SiteSettings_ContactFooter, 
            T.ContactUrl AS SiteSettings_ContactUrl, 
            T.RolesFooter AS SiteSettings_RolesFooter, 
            T.RolesUrl AS SiteSettings_RolesUrl, 
            T.ContactNumberFooter AS SiteSettings_ContactNumberFooter, 
            T.EmailFooter AS SiteSettings_EmailFooter, 
            T.AddresFooter AS SiteSettings_AddresFooter, 
            T.ContentFooter AS SiteSettings_ContentFooter, 
            T.CopyrightFooter AS SiteSettings_CopyrightFooter, 
            T.LoginFooter AS SiteSettings_LoginFooter, 
            T.LoginUrl AS SiteSettings_LoginUrl, 
            True AS _from0
        FROM ContextDb.SiteSettings AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.SiteSettings.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView53()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SiteSettings
        [OPMS.Data.Context.SiteSettings](T1.SiteSettings_Id, T1.SiteSettings_SiteName, T1.SiteSettings_IsRegister, T1.SiteSettings_SiteFooter, T1.SiteSettings_FavIconURL, T1.SiteSettings_SiteOwner, T1.SiteSettings_CustomCSS, T1.SiteSettings_GoogleSiteVerification, T1.SiteSettings_GoogelAds, T1.SiteSettings_IsCustomCSSOn, T1.SiteSettings_CustomJS, T1.SiteSettings_IsCustomJsOn, T1.SiteSettings_SiteLastUpdated, T1.SiteSettings_UpdateBy, T1.SiteSettings_HomeFooter, T1.SiteSettings_HomeUrl, T1.SiteSettings_AboutFooter, T1.SiteSettings_AboutUrl, T1.SiteSettings_ContactFooter, T1.SiteSettings_ContactUrl, T1.SiteSettings_RolesFooter, T1.SiteSettings_RolesUrl, T1.SiteSettings_ContactNumberFooter, T1.SiteSettings_EmailFooter, T1.SiteSettings_AddresFooter, T1.SiteSettings_ContentFooter, T1.SiteSettings_CopyrightFooter, T1.SiteSettings_LoginFooter, T1.SiteSettings_LoginUrl)
    FROM (
        SELECT 
            T.Id AS SiteSettings_Id, 
            T.SiteName AS SiteSettings_SiteName, 
            T.IsRegister AS SiteSettings_IsRegister, 
            T.SiteFooter AS SiteSettings_SiteFooter, 
            T.FavIconURL AS SiteSettings_FavIconURL, 
            T.SiteOwner AS SiteSettings_SiteOwner, 
            T.CustomCSS AS SiteSettings_CustomCSS, 
            T.GoogleSiteVerification AS SiteSettings_GoogleSiteVerification, 
            T.GoogelAds AS SiteSettings_GoogelAds, 
            T.IsCustomCSSOn AS SiteSettings_IsCustomCSSOn, 
            T.CustomJS AS SiteSettings_CustomJS, 
            T.IsCustomJsOn AS SiteSettings_IsCustomJsOn, 
            T.SiteLastUpdated AS SiteSettings_SiteLastUpdated, 
            T.UpdateBy AS SiteSettings_UpdateBy, 
            T.HomeFooter AS SiteSettings_HomeFooter, 
            T.HomeUrl AS SiteSettings_HomeUrl, 
            T.AboutFooter AS SiteSettings_AboutFooter, 
            T.AboutUrl AS SiteSettings_AboutUrl, 
            T.ContactFooter AS SiteSettings_ContactFooter, 
            T.ContactUrl AS SiteSettings_ContactUrl, 
            T.RolesFooter AS SiteSettings_RolesFooter, 
            T.RolesUrl AS SiteSettings_RolesUrl, 
            T.ContactNumberFooter AS SiteSettings_ContactNumberFooter, 
            T.EmailFooter AS SiteSettings_EmailFooter, 
            T.AddresFooter AS SiteSettings_AddresFooter, 
            T.ContentFooter AS SiteSettings_ContentFooter, 
            T.CopyrightFooter AS SiteSettings_CopyrightFooter, 
            T.LoginFooter AS SiteSettings_LoginFooter, 
            T.LoginUrl AS SiteSettings_LoginUrl, 
            True AS _from0
        FROM CodeFirstDatabase.SiteSettings AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.SWBanner.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView54()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SWBanner
        [CodeFirstDatabaseSchema.SWBanner](T1.SWBanner_Id, T1.SWBanner_BTitle, T1.SWBanner_BSubTitle, T1.SWBanner_BContent, T1.SWBanner_BImage, T1.SWBanner_BButton, T1.SWBanner_BButtonUrl)
    FROM (
        SELECT 
            T.Id AS SWBanner_Id, 
            T.BTitle AS SWBanner_BTitle, 
            T.BSubTitle AS SWBanner_BSubTitle, 
            T.BContent AS SWBanner_BContent, 
            T.BImage AS SWBanner_BImage, 
            T.BButton AS SWBanner_BButton, 
            T.BButtonUrl AS SWBanner_BButtonUrl, 
            True AS _from0
        FROM ContextDb.SWBanner AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.SWorkerPage.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView55()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SWorkerPage
        [CodeFirstDatabaseSchema.SWorkerPage](T1.SWorkerPage_Id, T1.SWorkerPage_Title, T1.SWorkerPage_Content, T1.SWorkerPage_ButtonUrl, T1.SWorkerPage_ButtonText, T1.SWorkerPage_SubContent, T1.SWorkerPage_GoogleMapAPIUrl, T1.SWorkerPage_IsSWorkertMetaDataOn, T1.SWorkerPage_MetaKeywordse, T1.SWorkerPage_MetaDescription, T1.SWorkerPage_IsVisibleToSearchEngine, T1.SWorkerPage_BannerId)
    FROM (
        SELECT 
            T.Id AS SWorkerPage_Id, 
            T.Title AS SWorkerPage_Title, 
            T.Content AS SWorkerPage_Content, 
            T.ButtonUrl AS SWorkerPage_ButtonUrl, 
            T.ButtonText AS SWorkerPage_ButtonText, 
            T.SubContent AS SWorkerPage_SubContent, 
            T.GoogleMapAPIUrl AS SWorkerPage_GoogleMapAPIUrl, 
            T.IsSWorkertMetaDataOn AS SWorkerPage_IsSWorkertMetaDataOn, 
            T.MetaKeywordse AS SWorkerPage_MetaKeywordse, 
            T.MetaDescription AS SWorkerPage_MetaDescription, 
            T.IsVisibleToSearchEngine AS SWorkerPage_IsVisibleToSearchEngine, 
            T.BannerId AS SWorkerPage_BannerId, 
            True AS _from0
        FROM ContextDb.SWorkerPage AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.SWBanner.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView56()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SWBanner
        [OPMS.Data.Context.SWBanner](T1.SWBanner_Id, T1.SWBanner_BTitle, T1.SWBanner_BSubTitle, T1.SWBanner_BContent, T1.SWBanner_BImage, T1.SWBanner_BButton, T1.SWBanner_BButtonUrl)
    FROM (
        SELECT 
            T.Id AS SWBanner_Id, 
            T.BTitle AS SWBanner_BTitle, 
            T.BSubTitle AS SWBanner_BSubTitle, 
            T.BContent AS SWBanner_BContent, 
            T.BImage AS SWBanner_BImage, 
            T.BButton AS SWBanner_BButton, 
            T.BButtonUrl AS SWBanner_BButtonUrl, 
            True AS _from0
        FROM CodeFirstDatabase.SWBanner AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.SWorkerPage.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView57()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SWorkerPage
        [OPMS.Data.Context.SWorkerPage](T1.SWorkerPage_Id, T1.SWorkerPage_Title, T1.SWorkerPage_Content, T1.SWorkerPage_ButtonUrl, T1.SWorkerPage_ButtonText, T1.SWorkerPage_SubContent, T1.SWorkerPage_GoogleMapAPIUrl, T1.SWorkerPage_IsSWorkertMetaDataOn, T1.SWorkerPage_MetaKeywordse, T1.SWorkerPage_MetaDescription, T1.SWorkerPage_IsVisibleToSearchEngine, T1.SWorkerPage_BannerId)
    FROM (
        SELECT 
            T.Id AS SWorkerPage_Id, 
            T.Title AS SWorkerPage_Title, 
            T.Content AS SWorkerPage_Content, 
            T.ButtonUrl AS SWorkerPage_ButtonUrl, 
            T.ButtonText AS SWorkerPage_ButtonText, 
            T.SubContent AS SWorkerPage_SubContent, 
            T.GoogleMapAPIUrl AS SWorkerPage_GoogleMapAPIUrl, 
            T.IsSWorkertMetaDataOn AS SWorkerPage_IsSWorkertMetaDataOn, 
            T.MetaKeywordse AS SWorkerPage_MetaKeywordse, 
            T.MetaDescription AS SWorkerPage_MetaDescription, 
            T.IsVisibleToSearchEngine AS SWorkerPage_IsVisibleToSearchEngine, 
            T.BannerId AS SWorkerPage_BannerId, 
            True AS _from0
        FROM CodeFirstDatabase.SWorkerPage AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.SWorkerProfile.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView58()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SWorkerProfile
        [CodeFirstDatabaseSchema.SWorkerProfile](T1.SWorkerProfile_Id, T1.SWorkerProfile_Title, T1.SWorkerProfile_ImageUrl, T1.SWorkerProfile_FullName, T1.SWorkerProfile_JobTitle, T1.SWorkerProfile_Content)
    FROM (
        SELECT 
            T.Id AS SWorkerProfile_Id, 
            T.Title AS SWorkerProfile_Title, 
            T.ImageUrl AS SWorkerProfile_ImageUrl, 
            T.FullName AS SWorkerProfile_FullName, 
            T.JobTitle AS SWorkerProfile_JobTitle, 
            T.Content AS SWorkerProfile_Content, 
            True AS _from0
        FROM ContextDb.SWorkerProfiles AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.SWorkerProfiles.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView59()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SWorkerProfiles
        [OPMS.Data.Context.SWorkerProfile](T1.SWorkerProfile_Id, T1.SWorkerProfile_Title, T1.SWorkerProfile_ImageUrl, T1.SWorkerProfile_FullName, T1.SWorkerProfile_JobTitle, T1.SWorkerProfile_Content)
    FROM (
        SELECT 
            T.Id AS SWorkerProfile_Id, 
            T.Title AS SWorkerProfile_Title, 
            T.ImageUrl AS SWorkerProfile_ImageUrl, 
            T.FullName AS SWorkerProfile_FullName, 
            T.JobTitle AS SWorkerProfile_JobTitle, 
            T.Content AS SWorkerProfile_Content, 
            True AS _from0
        FROM CodeFirstDatabase.SWorkerProfile AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.UserLocation.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView60()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserLocation
        [CodeFirstDatabaseSchema.UserLocation](T1.UserLocation_Id, T1.UserLocation_Ip, T1.UserLocation_UserAgint, T1.UserLocation_ActionName, T1.UserLocation_ControllerName, T1.UserLocation_LoginUser, T1.UserLocation_UserBrowser, T1.UserLocation_DateTime, T1.UserLocation_DeviceName, T1.UserLocation_AuthenticationActivity)
    FROM (
        SELECT 
            T.Id AS UserLocation_Id, 
            T.Ip AS UserLocation_Ip, 
            T.UserAgint AS UserLocation_UserAgint, 
            T.ActionName AS UserLocation_ActionName, 
            T.ControllerName AS UserLocation_ControllerName, 
            T.LoginUser AS UserLocation_LoginUser, 
            T.UserBrowser AS UserLocation_UserBrowser, 
            T.DateTime AS UserLocation_DateTime, 
            T.DeviceName AS UserLocation_DeviceName, 
            T.AuthenticationActivity AS UserLocation_AuthenticationActivity, 
            True AS _from0
        FROM ContextDb.UserLocations AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ContextDb.UserLocations.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView61()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserLocations
        [OPMS.Data.Context.UserLocation](T1.UserLocation_Id, T1.UserLocation_Ip, T1.UserLocation_UserAgint, T1.UserLocation_ActionName, T1.UserLocation_ControllerName, T1.UserLocation_LoginUser, T1.UserLocation_UserBrowser, T1.UserLocation_DateTime, T1.UserLocation_DeviceName, T1.UserLocation_AuthenticationActivity)
    FROM (
        SELECT 
            T.Id AS UserLocation_Id, 
            T.Ip AS UserLocation_Ip, 
            T.UserAgint AS UserLocation_UserAgint, 
            T.ActionName AS UserLocation_ActionName, 
            T.ControllerName AS UserLocation_ControllerName, 
            T.LoginUser AS UserLocation_LoginUser, 
            T.UserBrowser AS UserLocation_UserBrowser, 
            T.DateTime AS UserLocation_DateTime, 
            T.DeviceName AS UserLocation_DeviceName, 
            T.AuthenticationActivity AS UserLocation_AuthenticationActivity, 
            True AS _from0
        FROM CodeFirstDatabase.UserLocation AS T
    ) AS T1");
        }
    }
}
